name: "Test Pull Request"

on:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: actions/setup-pnpm@v4
      - run: IMAGE_STATS_ONLY=true pnpm exec eleventy --config=eleventy.config.js
      